[build]
  command = "npm run build"  # Adjust if your build command is different
  publish = "dist"  # Ensure this matches your Webpack output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
